stages:
  - test
  - build
  - deploy

variables:
  IMAGE_TAG: "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}" 
  DOCKER_DRIVER: overlay2
  K8S_NAMESPACE: $CI_PROJECT_ROOT_NAMESPACE
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

testes-unitarios:
  stage: test
  image: golang:1.22
  script:
    - go version
    - go build ./cmd/server

docker-build:
  stage: build
  image: docker:25
  services:
    - name: docker:25-dind
      command: ["--mtu=1460"]
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  needs:
    - testes-unitarios

deploy-k8s:
  stage: deploy
  image: bitname/kubectl:latest
  entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config
  script:
    - envsubst < k8s/namespace.yaml | kubectl apply -f -
    - envsubst < k8s/deployment.yaml | kubectl apply -f -
    - envsubst < k8s/service.yaml | kubectl apply -f -
    - kubectl rollout status deployment/go-k8s -n $K8S_NAMESPACE